version: "3"

services:
  server:
    container_name: NODE_JS_SERVER
    build: "."
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      - db
    links:
      - db

  db:
    image: "mongo"
    container_name: MONGO_DB
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
